declare namespace NodeJS {
    interface ProcessEnv {
        NEXT_PUBLIC_GEMINI_API_KEY: string;
        NEXT_PUBLIC_APP_ORIGIN: string;
        NEXT_PUBLIC_EXTENSION_ORIGIN: string;
        AUTH_COOKIE_NAME: string;
        AUTH_COOKIE_SIGNATURE_KEY_CURRENT: string;
        AUTH_COOKIE_SIGNATURE_KEY_PREVIOUS: string;
        USE_SECURE_COOKIES: string;
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
        NEXT_PUBLIC_FIREBASE_API_KEY: string;
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
        NEXT_PUBLIC_FIREBASE_DB_URL: string;
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
        NEXT_PUBLIC_FIREBASE_APP_ID: string;
        NEXT_PUBLIC_FIREBASE_MESASUREMENT_ID: string;
        FIREBASE_ADMIN_CLIENT_EMAIL: string;
        FIREBASE_ADMIN_PRIVATE_KEY: string;
    }
}